stages:
    - deploy

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

deploy-prod-job:
    stage: deploy
    only:
        - master
    script:
        - echo "$DEPLOY_PRIVATE_SSH_KEY_PROD" | tr -d '\r' | ssh-add -
        - echo "Deploying the PROD project..."
        - ssh -tt -o StrictHostKeyChecking=no $DEPLOY_HOST_PROD
            "cd /root/sites/framework} &&
            git reset --hard &&
            git pull &&
            docker compose up -d"